### ISSUE TITLE
read creation date too

### ISSUE THREAD

**Issue by frisi** [collective/unweb.iptc#1]
i'd like to add the functionality that the creation date of an image also gets added to plone's metadata.

do not yet know whether it's better (and possiblte at all) to set the creationdate (/created), or just use the effectivedate for this information.

pro for effective: can be edited ttw
pro for created: better semantic, con: not editable ttw

@d-mo and @jensens since you are the only commiters to this repos (and so possibly using this): what are your opinions on that?

**Comment by jensens** [comment]
so, i just fixed some nasty thing iirc. 
but +1 for using creation date as creation date :)

**Comment by d-mo** [comment]
+1 for created
